name: Compile ESP32 Binary
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    # This environment variable fixes the Node.js 20 warning
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      - name: Install ESP32 Core
        run: |
          arduino-cli core update-index --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          arduino-cli core install esp32:esp32 --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json

      - name: Compile
        run: |
          # We add --verbose to see EXACTLY why the code failed if it happens again
          arduino-cli compile --verbose --fqbn esp32:esp32:esp32 --output-dir ./build .

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: compiled-bin
          path: ./build/*.bin
